# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Control all joints
arm_controller:
  type: "arm_control/JointTrajectoryController"
  joints:
    - base_link__link_01
    - link_01__link_02
    - link_02__link_03
    - link_03__link_04
    - link_04__link_05

  gains:
    base_link__link_01: {p: 200,  d: 10}
    link_01__link_02: {p: 200,  d: 10}
    link_02__link_03: {p: 200,  d: 10}
    link_03__link_04: {p: 150,  d: 10}
    link_04__link_05: {p: 150,  d: 10}
